Dev Optimized Communications PageRank version
jgurhem/TBSLA pull request #1
Opened 2022-08-28 14:36 UTC by nicochart

New version of PageRank, optimized for testing with the Torus node allocation Method on Fugaku, developed during my end-of-studies engineering internship.

2022-09-13 12:32 UTC, jgurhem requested changes

2022-09-13 12:32 UTC, jgurhem commented on tools/jobscripts_fugaku/mpi_cmg/random_stoch/1024N.sh
> +#PJM -L  "elapse=2:00:00"
La plupart de ces scripts ne sont pas nécessaires. Je génère ce genre de script automatiquement via les utilitaires dans tools/ si besoin. De plus, je ne pense pas que tes pdf doivent aussi être dans ce repo !

2022-09-14 21:52 UTC, nicochart commented on tools/jobscripts_fugaku/mpi_cmg/random_stoch/1024N.sh
> +#PJM -L  "elapse=2:00:00"
J'ai mis à jour tout cela : j'ai supprimé les jobscripts et les pdfs.

J'ai renvoyé (par le readme) vers un autre repo où je les ai publié :
Il me semble important que les futurs personnes qui travaillent sur le projet (éventuellement des étudiants polytech en projet bientôt) aient directement accès aux pdfs que j'ai rédigé pour comprendre les algo.

2022-09-15 20:18 UTC, jgurhem approved these changes

2022-09-15 20:19 UTC, merged